// SPDX-License-Identifier: Apache-2.0

import {
  ExternalEngine,
  MeridianDeployment,
  catalogNames,
  getEngineProfile,
  type CatalogProviderV1,
  type MeridianResourceRequirementV1,
} from "../src/index.js";

const catalogFingerprint = `sha256:${"a".repeat(64)}`;
const schemaFingerprint = `sha256:${"b".repeat(64)}`;
const physicalFingerprint = `sha256:${"c".repeat(64)}`;
const profile = getEngineProfile("postgresql-postgis-local-single-primary");

const catalogs: readonly CatalogProviderV1[] = catalogNames.map((name) => ({
  name,
  package: `meridian-storage-${name}`,
  contract: "1.0.0",
  requiredFingerprint: catalogFingerprint,
}));

const resource: MeridianResourceRequirementV1 = {
  selector: { catalog: "structured", namespace: "orders", name: "records" },
  schemas: [
    {
      providerId: "orders-schema",
      package: "example-orders-schema",
      version: "1.0.0",
      fingerprint: schemaFingerprint,
    },
  ],
  operations: [
    {
      contract: "meridian.structured.get",
      version: "1.0.0",
      guarantees: ["bound-parameters", "scope-injected"],
      limits: { maxPageSize: 100 },
    },
  ],
  guarantees: { required: [] },
  limits: { values: {} },
  dataClass: "internal-operational",
};

const engine = new ExternalEngine("orders-postgresql", {
  binding: {
    bindingId: "orders-db",
    profileId: profile.id,
    // Generated by the selected Adapter's public expected-fingerprint helper
    // from these exact Engine settings, or obtained from an authenticated probe.
    requiredCapabilityFingerprint:
      "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    acl: { provider: "policy-registry", reference: "orders-runtime" },
    migration: {
      contract: "meridian.migration.apply",
      version: "1.0.0",
      appliedFingerprint: schemaFingerprint,
    },
    observability: { enabled: false, labels: { service: "orders" } },
  },
  connection: {
    physicalNamespace: "orders",
    identityRef: { provider: "workload-identity", reference: "orders-runtime" },
    secretRef: { provider: "secret-manager", reference: "orders/database" },
    tls: {
      mode: "server",
      serverName: "postgres.example",
      caRef: { provider: "secret-manager", reference: "orders/postgres-ca" },
    },
    endpoint: "postgresql://postgres.example:5432/orders",
    requiredPhysicalFingerprint: physicalFingerprint,
    settings: { connectTimeoutSeconds: 10 },
  },
});

export const deployment = new MeridianDeployment("orders-storage", {
  profile: "production",
  catalogs,
  schemaProviders: [
    {
      id: "orders-schema",
      package: "example-orders-schema",
      contract: "1.0.0",
      requiredFingerprint: schemaFingerprint,
    },
  ],
  resources: [resource],
  engines: [engine],
  placements: [
    {
      id: "orders-primary",
      selector: { resources: [resource.selector], catalog: null, labels: {} },
      bindingId: engine.bindingId,
      extensions: { selection: "one-primary" },
    },
  ],
});

export const runtimeConfigJson = deployment.runtimeConfigJson;
export const resourceCapability =
  deployment.bindingOutputs["structured:orders.records"];
