# SPDX-License-Identifier: Apache-2.0
"""Stable, redaction-safe construct planning errors."""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    """Machine-readable failure codes emitted before resources are provisioned."""

    AMBIGUOUS_PLACEMENT = "MERIDIAN_CONSTRUCTS_AMBIGUOUS_PLACEMENT"
    DUPLICATE_BINDING = "MERIDIAN_CONSTRUCTS_DUPLICATE_BINDING"
    DUPLICATE_PLACEMENT = "MERIDIAN_CONSTRUCTS_DUPLICATE_PLACEMENT"
    DUPLICATE_RESOURCE = "MERIDIAN_CONSTRUCTS_DUPLICATE_RESOURCE"
    INCOMPATIBLE_CATALOG = "MERIDIAN_CONSTRUCTS_INCOMPATIBLE_CATALOG"
    INCOMPATIBLE_GUARANTEE = "MERIDIAN_CONSTRUCTS_INCOMPATIBLE_GUARANTEE"
    INCOMPATIBLE_OPERATION = "MERIDIAN_CONSTRUCTS_INCOMPATIBLE_OPERATION"
    INVALID_ENDPOINT = "MERIDIAN_CONSTRUCTS_INVALID_ENDPOINT"
    INVALID_INPUT = "MERIDIAN_CONSTRUCTS_INVALID_INPUT"
    INVALID_REFERENCE = "MERIDIAN_CONSTRUCTS_INVALID_REFERENCE"
    LIMIT_EXCEEDED = "MERIDIAN_CONSTRUCTS_LIMIT_EXCEEDED"
    MISSING_PLACEMENT = "MERIDIAN_CONSTRUCTS_MISSING_PLACEMENT"
    PROFILE_NOT_FOUND = "MERIDIAN_CONSTRUCTS_PROFILE_NOT_FOUND"
    SECRET_MATERIAL = "MERIDIAN_CONSTRUCTS_SECRET_MATERIAL"  # noqa: S105  # nosec B105
    VERSION_NOT_PINNED = "MERIDIAN_CONSTRUCTS_VERSION_NOT_PINNED"


class ConstructError(ValueError):
    """A deterministic validation error that never includes secret material."""

    def __init__(self, code: ErrorCode, message: str) -> None:
        self.code = code
        super().__init__(f"{code}: {message}")


__all__ = ["ConstructError", "ErrorCode"]
